---
layout: post
title: Alexandro Jodorowsky apprend la magie avec Pachita
date: 2014-10-22 12:59:12.000000000 +02:00
categories:
- Divers
tags: []
status: publish
type: post
published: true
meta:
  _edit_last: '2'
author:
  first_name: Nico
excerpt:
---
<p>&nbsp;</p>
<div style="text-align: center;">
<p>Extrait de</p>
<p><em><a href="http://www.amazon.fr/dp/2226125388" target="_blank">Alexandro Jodorowsky<br />
Le théâtre de la guérison<br />
Espaces libres — Albin Michel<br />
pp. 156–169</a></em></p>
<p><a href="http://www.amazon.fr/dp/2226125388" target="_blank"><img class="aligncenter wp-image-3671 size-medium" src="{{ site.url }}/assets/416WBZMA0RL-184x300.jpg" alt="Le théâtre de la guérison" width="184" height="300" /></a></p>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<hr />
<p><em>Certes ! Selon vous, que faut-il en conclure ?</em></p>
<p>Jamais je n’affirmerai que les manipulations de Pachita étaient de vraies opérations ; mais jamais je n’affirmerai le contraire... Et j’ai fini par conclure que cela n’avait pas d’importance. C’est notre croyance en un monde « objectif », notre mentalité moderne soi-disant rationnelle qui fait que ce genre de questions nous tourmente. Nous prétendons toujours nous situer en tant qu’observateur détaché d’un phénomène supposé extérieur et dont les mécanismes doivent être clairement cernés. Dans la mentalité « chamanique », par contre, ce type de problèmes ne se pose même pas. Il n’y a pas de sujet observateur et d’objet observé, il y a le monde en tant que rêve grouillant de signes et de symboles, champ d’interaction où se rencontrent des forces et influences multiples. Dans ce contexte, savoir si les opérations de Pachita sont « réelles » ou non s’avère incongru. Quel réel ? Dès lors que l’on pénètre dans le champ énergétique de la sorcière, que l’on s’incorpore à sa réalité et qu’elle entre dans la tienne, vous évoluez tous deux au sein d’un réel où les pratiques de guérison se révèlent opérantes. Et le fait est que nombre de gens furent bel et bien guéris ! En outre, si je reviens au point de vue dit « objectif », jamais je n’ai pu la prendre en défaut, jamais je n’ai pu déceler le « truc », même en me tenant juste à côté d’elle semaine après semaine, pendant des heures... Quoi qu’il en soit, on ne peut que reconnaître le génie de Pachita. Si c’était du théâtre, quelle actrice ! S’il s’agissait de prestidigitation, cette bonne femme était le plus grand prestidigitateur de tous les temps ! Et quelle psychologue...</p>
<p><em>Que vous a-t-elle appris ? Qu’en avez-vous retiré pour votre pratique future de la psychomagie ?</em></p>
<p>J’ai d’abord appris comment traiter les gens. Grâce à elle, j’ai compris que toute personne — ou presque — est un enfant, parfois un adolescent. Chaque fois que quelqu’un venait à elle, elle commençait immédiatement par le toucher avec ses mains, établissant ainsi un rapport sensoriel et mettant les gens en confiance. Il se produisait un phénomène étrange : dès que l’on sentait sur soi les mains de cette vieille femme, elle nous apparaissait comme la mère universelle et il n’y avait plus moyen de lui résister. J’en témoigne d’autant plus que j’étais à l’époque extrêmement rétif aux maîtres et refusais de me soumettre à qui que ce soit. Mais à son contact, mes résistances fondaient comme neige au soleil. Pachita savait qu’en l’adulte, même affirmé, sommeille un enfant avide d’être aimé et qu’une certaine manière de toucher ferait bien plus que des paroles pour d’emblée instaurer la confiance et mettre le sujet en état de réceptivité. Ce toucher paraissait aussi lui permettre d’établir un diagnostic. Je me souviens par exemple du jour où je lui ai amené un ami français. Il souffrait depuis un certain temps et il avait fallu six mois aux médecins français pour découvrir la présence d’un polype à l’intestin. Pachita lui a passé les mains sur le corps et s’est aussitôt prononcée sur la présence d’une grosseur à l’intestin. Mon ami n’en revenait pas !</p>
<p>Mais outre ces facultés quasi divinatoires, cette sorcière se livrait parfois à ce qui m’apparaît aujourd’hui comme de merveilleux actes psychomagiques : elle a un jour reçu un homme qui était au bord du suicide parce qu’il ne supportait pas de perdre ses cheveux à trente ans. Il avait essayé tous les traitements possibles, sans succès, et ne pouvait admettre de se voir chauve. L’« hermanito » lui a demandé par la bouche de la vieille : « Crois-tu en moi ? » Il a répondu par l’affirmative et, de fait, il avait foi en Pachita. L’esprit lui a alors donné l’instruction suivante : « Procure-toi un kilo d’excréments de rat, pisse dedans, malaxe le tout pour en faire une pâte que tu t’appliqueras sur la tête. Cette médecine fera repousser tes cheveux. » L’homme a vaguement protesté mais Pachita a insisté, lui disant que s’il voulait éviter la calvitie, il lui faudrait en passer par là. Il s’est incliné et a décidé de se soumettre à ce traitement incongru. Trois mois plus tard, il est revenu et s’est adressé à la vieille : « Il est très difficile de trouver des excréments de rat, mais j’ai fini par dénicher un laboratoire élevant des rats blancs. J’ai donné la pièce à un laborantin qui a consenti à conserver les excréments pour me les donner. Lorsque j’ai eu le kilo, j’ai pissé dessus, fait la pâte, pour soudain me rendre compte que cela m’était égal de ne plus avoir de cheveux. Aussi n’ai-je pas appliqué la mixture, désormais décidé à me contenter de mon sort. »</p>
<p>J’y ai vu un acte psychomagique essentiel. Pachita lui a demandé un prix qu’il n’était pas vraiment prêt à payer. Se trouvant mis au pied du mur, au moment de passer à l’acte, il s’est rendu compte qu’il pouvait parfaitement accepter son sort. Confronté à la réalité de l’acte difficile qui lui était demandé, il a vu qu’il préférait demeurer chauve. Il est sorti de son monde de pensées, de son imaginaire, pour regarder le réel en face. Ces directives à première vue absurdes lui ont donc donné l’occasion de mûrir, elles l’ont fait passer par tout un processus au terme duquel il lui est devenu possible de s’accepter tel qu’il était. C’est bien ainsi que je conçois la psychomagie. Il n’était pas rare que Pachita entraîne les gens dans une démarche bizarre destinée, en fin de compte, à les réconcilier avec un aspect d’eux-mêmes. Je me souviens d’une personne qui avait un gros problème par rapport à l’argent et ne parvenait pas à gagner sa vie. La vieille lui a imposé un étrange cérémonial : le « patient » devait chaque nuit uriner dans un pot de chambre jusqu’à le remplir. Il lui fallait ensuite laisser le pot sous son lit et dormir pendant trente jours au-dessus de son pipi. En tant que témoin de cette consultation, je me suis bien sûr demandé quelle pouvait en être la signification. Peu à peu, j’ai commencé à en entrevoir le sens : si une personne ne souffrant d’aucun handicap particulier sur le plan physique ou intellectuel ne parvient pas à gagner sa vie, c’est qu’elle ne le veut pas. Une part d’elle-même s’y oppose et se trouve en conflit avec l’argent. Or, suivre les directives de Pachita, c’est très vite s’exposer à un véritable supplice : il ne faut pas longtemps pour que l’urine conservée jour après jour sous le lit dégage une odeur pestilentielle. Contraint de dormir au-dessus du pot, le patient marine dans ses propres remugles, en vient à baigner dans les effluves de ses déchets. Par ailleurs, un tel exercice exige que l’on se sacrifie et développe la volonté. Il en faut pour supporter les retrouvailles nocturnes avec son pipi...</p>
<p><em>Je n’en doute pas, Alexandro, mais quel rapport avec l’argent ?</em></p>
<p>D’abord un rapport symbolique : le pipi est jaune, comme l’or. Mais en même temps, c’est un déchet... Produire des déchets procède d’un besoin naturel ; et le besoin d’uriner ou de déféquer est lui même une conséquence d’un autre besoin, celui de manger et de boire. Or, pour subvenir à ses besoins, il faut gagner de l’argent. L’argent en tant qu’énergie s’inscrit dans la chaîne des besoins et doit donc circuler... La personne ne gagnait pas sa vie parce qu’elle éprouvait une répulsion à l’égard de l’argent considéré comme sale, vil... L’énergie argent était chez elle bloquée. Il lui en fallait mais elle ne voulait pas se trouver impliquée dans sa manipulation. Une part d’elle-même refusait de prendre part à ce mouvement qui fait que l’argent rentre et sort, se transforme en nourriture... Elle répugnait à reconnaître la place légitime de l’« or » dans ce réseau que constitue toute existence. Pachita l’a obligée à domestiquer cette peur. Se retrouvant chaque nuit seul avec son pipi stagnant, le patient a subtilement compris que l’or/excrément n’est « sale » que s’il ne circule pas. Si on refuse de le voir et qu’on le pose sous le lit, les ennuis commencent... l’« or » ne puait que parce qu’il lui avait assigné une place honteuse. Enfin, ainsi que je l’ai déjà mentionné, le seul fait de pratiquer l’exercice jusqu’au bout l’a obligé à faire preuve de volonté, qualité indispensable pour gagner normalement sa vie.</p>
<p><em>À propos, Pachita demandait-elle à ses patients de la payer ?</em></p>
<p>Non, elle ne demandait pas d’honoraires mais les gens faisaient des donations. Lorsqu’elle opérait, il y avait toujours à proximité un panier avec une grande poche dans lequel les patients déposaient ce qu’ils voulaient. On ne pouvait l’accuser d’être à la tête d’un « business ». Reste que ceux qui en avaient les moyens la payaient bien ; c’était en effet une expérience sans prix que de se faire soigner par cette femme... Elle ne soignait pas pour gagner de l’argent ; elle gagnait de l’argent parce qu’elle guérissait.</p>
<p><em>Revenons à votre expérience et à ce que cette rencontre vous a apporté du point de vue de la psychomagie...</em></p>
<p>Bueno, dans <em>La Tricherie sacrée</em>, j’ai déjà raconté l’opération que j’ai moi-même subi. Je ne vais donc pas y revenir. En fait, Pachita mériterait qu’on lui consacre un livre.</p>
<p>Sa contribution à la psychomagie est aussi simple qu’essentielle : en l’observant, j’ai découvert que lorsque l’on fait mine d’opérer, le corps humain réagit comme s’il avait subi une véritable intervention. Si je vous annonce que je vais vous ouvrir le ventre pour vous enlever un morceau de foie, que je vous allonge sur une table et reproduis exactement tous les bruits, toutes les odeurs et les manipulations, si vous sentez le couteau se poser sur votre peau, si vous voyez le sang gicler, si vous avez la sensation que mes mains fouillent vos entrailles et en retirent quelque chose, vous voilà « opéré ». Le corps humain accepte directement et naïvement le langage symbolique, à la manière d’un enfant. Pachita le savait et était passée maître en l’art d’utiliser ce vocabulaire de manière, c’est le cas de le dire, opérationnelle.</p>
<p><em>Donc, pour vous, c’était avant tout une experte en communication symbolique ?</em></p>
<p>Absolument. Elle était d’ailleurs très attentive aux objets, aux bijoux que l’on portait. Je me souviens d’une femme portant un bracelet ovale à l’intérieur duquel, dans un petit trou également ovale, était incrustée une montre. C’était évidemment un cadeau de sa mère et Pachita a tout de suite vu que cette dame ne réglerait pas ses problèmes tant qu’elle ne se serait pas dégagée de l’emprise de maman. Faut-il le préciser, le trou symbolisait la mère dans le sein de laquelle la fille-montre était demeurée... Pachita a d’instinct décrypté le message symbolique et préconisé tout un rituel pour se défaire de l’objet. Pour elle, rien n’était anodin, le monde était vraiment une forêt de symboles en constante interaction. C’est à son contact que je me suis ouvert au langage des objets, à la signification que revêtent, par exemple, les cadeaux : tout présent a un sens, s’inscrit dans une dynamique de possession et de communication. De même, le fait d’oublier quelque chose chez un ami ou dans un lieu public n’a rien de gratuit... La sorcellerie primitive connaît le mécanisme de ces interactions et en a plus ou moins la maîtrise. Mais il s’agit bien sûr d’une connaissance intuitive et non intellectuelle ou scientifique. Le sorcier ou chaman serait probablement incapable de tenir un discours élaboré sur sa propre pratique ; pour cela, il lui faudrait pouvoir se situer à l’extérieur, se regarder agir et décrypter son fonctionnement. Or, sa force réside précisément dans le fait qu’il entretient avec le monde un rapport tout intérieur.</p>
<p>Il n’est pas le spectateur d’un monde « objectif » inanimé mais partie intégrante d’un univers subjectif dans lequel tout est vivant. Aussi Pachita percevait-elle les maladies comme des êtres animés : la tumeur était une créature maléfique qui méritait d’être brûlée vive et l’on entendait soudain comme des piaillements d’oiseau. Parfois, la sorcière extirpait du corps malade une forme en mouvement que l’on voyait s’agiter dans la pénombre comme une marionnette. Elle concrétisait la maladie qui perdait ainsi son statut d’ennemi invisible — et de ce fait d’autant plus menaçant — pour s’incarner en une figure vaguement grotesque susceptible d’être mise à mort. Du ventre d’un patient homosexuel, je l’ai vue sortir un phallus noir soufflant comme un crapaud...</p>
<p><em>Voilà qui eût été digne de votre happening... Ce sont des scènes « panique » que vous décrivez là...</em></p>
<p>C’était du Goya ! Je ne sais comment elle s’y prenait pour nous entraîner dans ce monde baroque... Transe, hallucination collective, prestidigitation géniale ? De toute manière, si tricherie il y avait, c’était une tricherie sacrée. Je veux dire par là que ses actes magiques se révélaient efficaces. Elle soulageait effectivement la plupart de ceux qui venaient la trouver. C’est pourquoi j’ai voulu l’observer et apprendre d’elle...</p>
<p><em>En vous situant cependant dans une logique quelque peu différente ; contrairement à un Castaneda qui, ayant reçu la transmission de Don Juan, devient lui-même un chaman, vous ne vous prétendez pas sorcier. Vous vous contentez d’assimiler certains principes universels pour les transposer dans une démarche non pas magique mais « psycho-magique »...</em></p>
<p>Oui, car je ne suis pas issu d’une culture dite « primitive ». À mon avis, on ne peut, sauf exception — je ne me prononce pas sur le cas de Castaneda —, devenir chaman ou sorcier si l’on n’est pas né dans un contexte primitif.</p>
<p>Même avec la meilleure volonté et la plus grande ouverture du monde, on ne se défait pas si facilement de tout son bagage occidental et rationnel.</p>
<p><em>En tant que Chilien d’origine russe ayant longtemps vécu au Mexique, vous n’êtes certes pas le prototype de l’Occidental adorateur de la Déesse Raison...</em></p>
<p>C’est vrai, je suis relativement fou, comme vous le savez...</p>
<p><em>Oh oui... (Soupir.)</em></p>
<p>Mais ma folie, ma démesure restent enracinées dans une culture malgré tout moderne. Que je le veuille ou non, je suis le produit d’une société matérialiste qui prétend entretenir avec le monde un rapport objectif. Mes audaces les plus extrêmes se situent toujours à l’intérieur de ce contexte dont nous ne pouvons pas sortir. Elles l’élargissent, peut-être, en font ressortir les contradictions et les impasses, mais elles ne l’annulent pas. Pour être sorcier ou chaman, il faut habiter un monde chamanique. En ce qui me concerne, je ne crois pas assez à la magie primitive pour moi-même devenir magicien.</p>
<p>C’est pourquoi, si j’ai voulu apprendre de Pachita, jamais je n’ai envisagé de recevoir son don pour à mon tour devenir guérisseur. Je dirais même que je m’y suis toujours refusé.</p>
<p><em>Sans doute ne croyez-vous pas assez à la magie pour devenir magicien ; mais vous y croyez tout de même...</em></p>
<p>Le fait est que si je ne puis en affirmer la véracité, je ne puis davantage en affirmer la fausseté. Mais je me suis très vite rendu compte que pour apprendre de Pachita, il me fallait adopter une position très nette et faire comme si je n’y croyais absolument pas.</p>
<p><em>Pourquoi ?</em></p>
<p>Si j’étais parti du principe que tout cela pouvait être vrai, que la magie en tant que telle était peut-être bien une réalité, je me serais très vite retrouvé dans une impasse. Je me serais efforcé de la suivre sur sa piste magique, de devenir moi-même magicien et ce en pure perte ou pour aboutir à des résultats très partiels et médiocres puisque, encore une fois, on ne peut changer de peau et devenir chaman en se disant que tout cela pourrait être vrai. Je me suis donc forcé à faire comme si ce ne pouvait être que faux. Par « faux », je ne veux pas dire inexistant — on était bien obligé de constater les guérisons et les phénomènes étranges qui survenaient autour de Pachita — mais ne relevant pas de la magie et susceptible d’être expliqué par un ensemble de lois psycho-physiologiques. Je me trouvais ainsi en mesure de véritablement apprendre de cette femme quelque chose que je pourrais ensuite réutiliser dans mon contexte.</p>
<p><em>À savoir...</em></p>
<p>À savoir la manière d’utiliser le langage des objets et le vocabulaire symbolique afin de produire chez l’autre certains effets ; bref, comment s’adresser à l’inconscient directement et dans sa propre langue, en passant soit par des mots, soit par des objets, soit par des actes. Voilà ce que j’ai appris de Pachita.</p>
<p><em>Pachita était certes exceptionnelle, mais elle s’inscrivait dans une tradition...</em></p>
<p>Bien sûr, et c’est pourquoi, après l’avoir rencontrée, je me suis avisé de la place de la magie dans toutes les cultures primitives. J’ai alors lu des centaines de livres sur ce sujet pour tenter de dégager des éléments universels dignes d’être utilisés de manière consciente dans ma propre pratique. Je ne vais pas m’étendre là-dessus mais vous donner quelques exemples. On retrouve partout l’idée de la puissance du verbe, la conviction que le désir exprimé sous la forme requise entraîne sa réalisation. Mais souvent, le nom du Dieu ou de l’esprit est encore renforcé par son association à une image. Comme quoi les anciens savaient intuitivement que l’inconscient n’est pas seulement réceptif au langage oral mais également aux formes, aux images, aux objets. En outre, les Égyptiens accordaient une importance capitale au mot écrit. Il ne s’agissait pas tant de dire que d’écrire. Dans la psychomagie, je demande souvent aux gens de rédiger des lettres, non pas tant pour ce qu’ils vont y signifier que parce que le seul acte d’écrire et d’envoyer la missive possède des vertus thérapeutiques. Une autre pratique universelle est celle de la purification, des ablutions rituelles. À Babylone, lors des cérémonies de guérison, les exorcistes enjoignaient au patient de se déshabiller, de jeter tous ses vieux vêtements, symboliques de l’ancien moi, et d’en revêtir de nouveaux. Les Égyptiens considéraient la purification comme préalable à la récitation des formules magiques, ainsi qu’en témoigne ce texte antique, dont j’ai oublié la provenance exacte mais qui m’a beaucoup inspiré : « Si un homme prononce cette formule à son propre usage, il doit être enduit d’huile et d’onguents, l’encensoir empli d’encens étant dans sa main ; il doit avoir du natrum d’une certaine qualité derrière les oreilles, une qualité différente de natrum étant dans sa bouche ; il doit être vêtu de vêtements neufs, après s’être lavé dans les eaux de la crue, avoir chaussé des sandales blanches, et avoir peint l’image de la déesse Ma’at à l’encre fraîche sur sa langue. » De même, il n’est pas rare que je demande à ceux qui viennent me consulter de prendre des bains, de procéder à certains lavements, car je sais que cet acte en apparence anodin influera grandement sur leur psychologie, les mettra dans des dispositions différentes. Si quelqu’un appréhende d’aller parler avec sa mère, je lui suggère de se rincer sept fois la bouche avant l’entretien et de s’emplir les poches de lavande. Ces détails vont suffire à lui faire aborder l’entrevue de manière différente.</p>
<p>Les Anciens attribuaient aussi un rôle d’allié à nombre d’objets symboliques : les textes magiques étaient récités au-dessus d’un insecte, d’un petit animal ou encore d’un collier. On utilisait également des bandes de lin, des figurines en cire, des plumes, des cheveux... Trouvant dans les textes la trace de ces pratiques, je me suis livré à une réflexion à propos des projections que font les gens sur les objets et me suis demandé comment les utiliser de manière positive. Les magiciens inscrivaient les noms de leurs ennemis sur des vases qui étaient ensuite brisés puis enterrés, ces destructions et disparitions devant entraîner celle des dits adversaires... Les portraits des « méchants » étaient peints sous les semelles des sandales royales, si bien que le roi piétinait chaque jour les envahisseurs potentiels. Dans la psychomagie, j’ai souvent recours aux mêmes principes « primitifs » mais à des fins exclusivement positives. Je conseille aux personnes de « charger » un objet, d’inscrire un nom... Dans le même ordre d’idée, les sorciers hittites m’ont fait découvrir les concepts de substitution, de remplacement et d’identification : le magicien, en effet, n’anéantit pas le mal ; il s’en empare en retrouvant ses origines, l’extirpe du corps ou de l’esprit de la victime pour le renvoyer aux enfers. D’après un vieux texte, « un objet sera attaché à la main droite et au pied droit de l’offrant, puis sera retiré et attaché ensuite sur une souris, tandis que l’officiant dira : “Je t’ai enlevé le mal et l’ai attaché à cette souris” ; sur quoi la souris sera libérée ». De même, il arrivait à Pachita d’enlever le mal pour le glisser vers une plante, un arbre ou un cactus, ce qui avait pour effet de faire périr la plante sous nos yeux... Il est également possible de remplacer la victime par un agneau, une chèvre : c’est le vieux concept du sacrifice de substitution où l’animal prend la place du malade. On noue le turban de ce dernier sur la tête de la chèvre à qui on tranche la gorge avec un couteau ayant auparavant touché celle de la personne souffrante... Selon la magie juive, les forces du mal peuvent être trompées, bernées, induites en erreur. On va alors déguiser la personne sur laquelle elles s’acharnent, modifier son nom... J’ai moi-même eu l’occasion de vérifier comment la modification du nom, ne serait-ce que dans son orthographe, pouvait s’avérer bénéfique. J’applique aussi ce principe à une carte du tarot : en principe, « la Maison Dieu » renvoie à une catastrophe ; mais pourquoi ne pas y voir « l’Âme et son Dieu », et, de ce fait, la charger positivement ? Tous ces vieux rituels m’ont aussi appris à utiliser l’enfouissement dans la terre lorsqu’il s’agit de faire un deuil.</p>
<p>Ce ne sont là que quelques exemples de principes universels de l’acte magique que je reprends pour les utiliser dans l’acte psychomagique, autrement dit dans une démarche thérapeutique.</p>
