---
layout: post
title: « Lettre à mon père »<br/>Adan Jodorowsky
date: 2015-04-11 10:53:14.000000000 +02:00
categories:
- Divers
tags: []
status: publish
type: post
published: true
meta:
  _edit_last: '2'
author:
  first_name: Nico
excerpt:
---
<p>Texte original : <a href="https://plancreateur.wordpress.com/2015/04/07/2101/" target="_blank">https://plancreateur.wordpress.com/2015/04/07/2101/</a><br />
<a href="http://hypnodingues.org/wp-content/uploads/2015/04/m-de-amador1.jpg"><img class="aligncenter size-full wp-image-3721" src="{{ site.url }}/assets/m-de-amador1.jpg" alt="m-de-amador1" width="640" height="636" /></a></p>
<p>Adan Jodorowsky à posté le texte suivant sur son compte Facebook quelques jours avant l’anniversaire de son père Alejandro :</p>
<p>Il y a quelques mois, j’ai écrit une lettre à mon père. Puis une femme que je ne connais pas, émue, m’a proposé de la traduire pour que les personnes qui parlent français puissent la lire. La voici.</p>
<p>Traduction: Mélanie Skriabine</p>
<h2>Lettre à mon père.</h2>
<p>« Cher père, Alejandro. Toi qui as toujours pensé qu’appeler « papa » son père est une erreur. Que « papa » et « maman » sont les premiers mots qu’un bébé est capable de prononcer et que de continuer de les appeler ainsi étant adulte signifie maintenir sa progéniture prisonnière d’un statut d’enfant. Toi, qui m’as dit: « Je ne m’appelle pas Papa, mon nom est Alejandro; je ne t’appelle pas Ada, dada ou adadá… »<br />
J’écris cette lettre ouverte parce que je veux que le monde sache que l’amour entre un père et son fils existe.</p>
<p>Je vois tant de cas de pères absents ou qui n’acceptent pas leurs enfants tels qu’ils sont. C’est pour cela qu’aujourd’hui je veux que tout le monde sache ce que peut être une vraie relation d’amour et de respect.<br />
J’espère que cela puisse être utile à cette planète; que cela serve d’exemple pour qu’une transformation positive s’opère en ce monde et que cessent de se créer les guerres qui ne sont que la conséquence de la colère refoulée.</p>
<p>T’appeler Alejandro ne m’a rien enlevé. Bien au contraire, je ne te voyais pas en tant que figure emblématique ou un être supérieur, je te voyais en tant qu’allié. Un être plein de bonté. T’appeler Alejandro est au monde la chose la plus tendre et merveilleuse qui soit. Et le fait que je me sois senti différent des autres enfants, a fait naître en moi une grande force.<br />
Tu ne m’as jamais éduqué dans la peur, tu ne m’as jamais frappé. Tu me parlais, m’expliquais tout et te préoccupais de m’enseigner tes pensées, me laissant libre d’être celui que je devais être et non celui que tu voulais que je sois. Te souviens-tu ? Tu avais pour habitude de t’asseoir près de moi et de me lire des contes japonais pour m’initier à une philosophie de vie.<br />
Tu as formé mon esprit pour me préparer comme un guerrier à recevoir les coups de la vie, à faire face aux discours stupides et à l’imbécilité humaine. Mais tu m’as aussi appris à reconnaitre la beauté dans la laideur. Je me souviens qu’un jour tu m’as dit « je vais t’apprendre à penser ». Nous étions en Espagne, en vacances sur une île et chaque matin tu me donnais des cours de réflexion. Chaque père devrait enseigner à son enfant la réflexion. Les enfants ne sont évidement pas stupides, ce que vous leur enseignez restera en eux à jamais. Grâce à ça, tu m’as marqué pour toujours.<br />
« Qu’est-ce que Dieu ? Qu’est-ce que l’univers ? Quel est notre but dans cet univers ? D’où viens-je ? Où vais-je ? Suis-je un corps habité d’une âme ou une âme habitant un corps ? Ta vérité est une vérité, pas la vérité…. »</p>
<p>Tu m’as appris à parler en tant que personne délicate et consciente. Quand j’étais enfant, tu me parlais doucement mais comme à un adulte, tu ne m’infantilisais pas en me parlant d’une voix de dessin animé. Les parents ont l’habitude de parler à leurs enfants comme s’ils étaient des poupées, mais toi, tu me parlais comme on parle à un être humain. Puis, tu m’as montré comment communiquer avec autrui et au lieu de parler par affirmation dans une conversation, j’ai appris à commencer mes phrases par: « selon ce que je pense et je peux me tromper…. »</p>
<p>Dans un combat, au lieu d’accuser l’autre, tu m’as appris à exprimer ce que je ressentais et ce qui était la cause de la discussion en moi. Tu ne m’as jamais fait part de tes difficultés financières, pour que l’argent ne représente pas un fardeau à mes yeux. Je vivais dans un paradis. Un enfant doit voir la vie comme un paradis. Le contraire produit des êtres angoissés, épouvantés à l’idée de devoir faire face à leur propre existence.<br />
Lorsque j’étais en colère, au lieu de me la faire contenir, tu m’as pris par la main pour m’amener dans le jardin et tu m’as fait détruire une chaise en mille morceaux. Tu ne peux pas t’imaginer le bonheur que m’a procuré le fait de mettre cette pauvre chaise en morceaux. Je t’ai dit: « Mais si je la casse, nous n’aurons plus de chaise… » ce à quoi tu as répondu que ce n’était pas important, que tu en achèterais une autre. Pour toi, le matériel n’avait pas d’importance, aucune valeur. La seule valeur à tes yeux était celle d’être humain.<br />
Au lieu de réprimer ma créativité, tu m’as acheté des pinceaux pour que je puisse peindre sur les murs de ma chambre. Rien ne m’était interdit. Lorsque je faisais une erreur, nous en parlions et la corrigions. Tu avais confiance en moi et dans mes propres limites, celles que je m’étais fixé moi-même. Je pouvais tout demander et faire. J’étais un enfant et nous parlions ouvertement de sexe, sans morale religieuse qui aurait pu nous laisser penser que c’était quelque chose de fou. Quand quelqu’un faisait l’amour dans la maison, le lendemain c’était la fête.<br />
Quand je voulais un instrument, au lieu de penser que c’était un caprice, tu m’achetais un piano, une trompette même si je ne l’utilisais qu’un seul jour. Tu disais que tout était utile dans la vie. Et c’est vrai, tout ce que j’ai demandé et que tu m’as donné dans mon enfance, m’a aidé. Absolument tout. Tu n’as jamais fixé aucune limite à ma créativité.Tu m’as appris comment méditer, tu m’as donné des livres.</p>
<p>Bien que ma mère et toi vous soyez séparés quand j’avais 8 ans, tu ne m’en as jamais dit de mal. Tu n’as pas essayé de détruire l’amour que je lui portais. Et tu as créé une relation d’amour entre mes frères et moi, sans esprit de compétition, nous aimant chacun différemment.</p>
<p>Tu m’as appris à croire que tout est possible dans la vie. Et comment ? Je vais te rappeler comment: un jour nous étions dans les rues de Paris cherchant une paire de chaussures et jusqu’à ce que je trouve la paire parfaite, nous n’allions pas laisser tomber. Nous sommes rentrés dans quinze boutiques jusqu’à ce que je trouve ce que je voulais vraiment. Merci père de mon coeur, grâce à ça, aujourd’hui, je ne laisse pas tomber et ce jusqu’à ce que je sois totalement satisfait de ce que je crée. Tu m’as aussi appris que lorsque quelque chose ne fonctionne pas, il est possible d’emprunter d’autres chemins qui mènent à ce que l’on désire et souhaite réaliser..</p>
<p>Quand je tombais dans la rue, tu me disais: « Samourai! » pour qu’à chaque pas, mon regard sur le monde soit conscient. Le Samourai ne se laisse jamais distraire. Je me sens vivant Alejandro, tellement vivant. Je ne t’ai jamais vu abattu. Tu te rends compte ? Tu ne t’es jamais plaint ou ne t’es laissé submergé par les difficultés de la vie. Tu ne m’as jamais montré tes angoisses. Tu m’as appris à être heureux, à penser que la vie est une fête. Tu m’as appris à ne pas me mettre à fumer quand les adolescents le font. Tu m’as expliqué que j’étais un enfant confiant et que je n’avais pas besoin d’une cigarette pour séduire, être adulte ou accepté des autres. Je me suis senti fort, tellement fort. Tu m’as appris à m’aimer et à respecter mon temple, mon corps.</p>
<p>Je te regardais écrire huit heures par jour, toute ta vie dédiée à ton art.<br />
Tu as trouvé l’amour réel à tes 75 ans. Tu as rencontré ta femme, Pascale et c’est la plus belle histoire que j’ai jamais vu de toute ma vie. Tu m’as permis de croire en l’union de deux âmes. Maintenant j’ai foi en l’amour à tout âge.</p>
<p>Quelques fois tu me demandes: « Comment te sens-tu mentalement, physiquement, sexuellement, émotionnellement ? » Tu communiques avec tout mon être. Quand je viens chez toi, je m’assois face à toi et tu me regardes, tu me parles de ta vie, demandes au sujet de la mienne et nous essayons de faire en sorte que nos monologues soient égaux en temps pour que nous puissions avoir une conversation équilibrée et que personne ne parle plus que l’autre.<br />
Tu t’inquiètes pour moi sans envahir mon espace. Mais tu me dis toujours que tu m’aimes. Chaque parent devrait le dire à son enfant.</p>
<p>Quand j’étais enfant et que tu devais partir voyager, tu m’appelais tous les jours, même si ce n’étais que deux minutes. C’était notre accord. Je ressentais ta présence. J’ai toujours ressenti que je pouvais compter sur toi. Chaque fois que tu disais quelque chose, tu le faisais. Et la chose la plus importante pour un enfant est qu’un père tienne ses promesses. Une fois, je suis parti en classe verte avec l’école et je me suis senti si mal avec les autres enfants, je me sentais si différent d’eux que je t’ai appelé en pleurs. La nuit même, tu es venu en voiture. Tu as fais 400 kilomètres pour venir me sortir de l’enfer. Et on est rentrés ensemble, en chantant. Tu m’as dit qu’un enfant ne doit jamais souffrir parce que les jeunes années sont sacrées.</p>
<p>Tu sentais toujours mes cheveux et ma peau en me disant que je sentais merveilleusement bon. Tu me disais toujours que j’avais du talent, que j’étais beau, que j’étais un prince. Tu me caressais, me touchais, me serrais dans tes bras. J’étais aimé. Le matin je frappais à ta porte et je courrais me glisser dans ton lit près de toi pour que tu me serres dans tes bras. Avec ma tête sur ta poitrine, j’écoutais ta respiration et ton coeur battre. Puis nous avions l’habitude de petit-déjeuner dans un café en face de la maison et tu me parlais de livres, de films, de découvertes que tu avais fait, de nouvelles idées spirituelles auxquelles tu avais pensé.</p>
<p>En ce moment même je pleure d’émotion parce que je n’ai jamais pris le temps de te dire tout cela. Tu es un père merveilleux. Mes larmes coulent, mais ces larmes sont des gouttes d’amour.</p>
<p>Tu m’as toujours emmené avec toi à tes conférences, tes séminaires, je t’ai vu soigner les gens, leur donner le sourire, calmer leurs peurs. Nous avons travaillé ensemble au théâtre, au cinéma, sur mes chansons. Comme c’est magnifique de pouvoir créer quelque chose en famille.<br />
Quand j’ai eu des doutes, tu as toujours été là. Tellement présent, que si tu n’étais pas à mes côtés aujourd’hui, je pourrais toujours entendre ta voix dans mon esprit, me conseillant. Je t’ai tatoué en moi, pour toujours.</p>
<p>Tu m’as sauvé Alejandro, de ce monde cruel, de ce chaos qu’est la vie. Tu m’as montré le plus beau de tout. Tu m’as tenu éloigné de toute pensée bourgeoise, de toute illusion, de toute pensée religieuse. Tu m’as appris à ne pas me fixer de limites. Tu m’as enseigné que je suis un homme libre. Libre de la folie des hommes, libre des guerres, des peurs. Tu m’as appris que la réalité dans laquelle je vis n’est pas la seule réalité, qu’il n’y a pas de limites, que mon horizon ne se limite pas à une maison, un pays ou un monde mais qu’il est l’univers tout entier, l’infini.</p>
<p>Pourquoi m’as-tu fait peindre sur les murs de ma chambre ? Je me le suis tellement demandé. Pourquoi me donner la liberté de faire ce que je voulais ? J’ai compris que tu m’avais enseigné à créer, à libérer mon esprit, à vivre sans contraintes, sans murs. Que ces murs étaient illusoires, invisibles et qu’en les peignant je pouvais passer à travers eux.</p>
<p>Tu m’as appris à parler: ni trop, ni pas assez, puis à mesurer le volume de ma voix, qu’elle soit une caresse pour les autres. Tu m’as appris à respecter le champs énergétique, l’aura d’autrui. Tu m’as appris à me fier aux arcanes du Tarot. Et tu m’as montré que les symboles sont de l’art. Tu m’as appris que la vie est magique et que les miracles sont partout. Tu m’as appris que Dieu est une énergie qui vit en nous et non un être sévère crée par des écrivains. Tu m’as ouvert un compte à la librairie et grâce à toi j’ai découvert la poésie. La Poésie ! Je me souviens que nous nous asseyions sur la table de la salle à manger et que chacun lisait son poème.</p>
<p>Tu n’as jamais eu d’amis superflus, les seules personnes qui entraient dans notre maison étaient celles que tu souhaitais aider ou des personnes talentueuses. Des poètes, des philosophes, des chanteurs, des médecins, des cordonniers, des saints, toutes sortes de personnes mais riches d’esprit. Tu n’as jamais perdu ton temps dans des discussions superficielles. Je ne t’ai jamais vu saoul ou drogué. Je t’ai seulement vu développer ton esprit et ton talent d’une façon positive afin de changer le monde et de lui apporter quelque chose.</p>
<p>Durant de nombreuses années, tu as eu le sentiment d’être un écrivain raté et regarde ce que tu as fait. A l’âge de soixante ans tu t’es libéré de ce sentiment, tu as publié plus de trente livres. Aujourd’hui, alors que tu as quatre-vingt-six ans tu es un écrivain avec un tel succès. Tout cela parce que tu crois en toi. Quel exemple tu es. Combien de personnes ne croient pas en ce qu’elles sont et cherchent une issue, incapables de voir que tout en elles est énergie vibrante depuis le premier jour! Tout est en nous!<br />
Tu m’as parlé de ce qu’est vieillir comme de quelque chose de beau et grâce à toi j’apprécie chaque année qui passe sans crainte de la mort. Grâce à toi je sais que tout est possible dans la vie, n’importe quand.</p>
<p>Je vois l’amour dans tes yeux lorsque tu me regardes. Tu m’as aimé et tellement donné que je t’aime sans limites. Tu as crée l’être qui écrit en ce moment. Tu as crée l’amour que je te porte. Tu as parfaitement appliqué cette phrase que tu as écrite et qui s’est révélée si vraie: Ce que tu donnes, tu te le donnes à toi-même, ce que tu ne donnes pas, tu te l’ôtes à toi-même.</p>
<p>Merci de me donner cette vie.</p>
<p>Ton fils Adan qui t’aime. »</p>
<p>Photo : Alejandra Vilchis pour « La mort d’Amador » Mars 2012</p>
<p>&nbsp;</p>
<p><a href="http://hypnodingues.org/wp-content/uploads/2015/04/cropped-img_7685-e1321364963851.jpg"><img class="aligncenter size-full wp-image-3722" src="{{ site.url }}/assets/cropped-img_7685-e1321364963851.jpg" alt="cropped-img_7685-e1321364963851" width="1152" height="2048" /></a></p>
