project:
  type: website
  output-dir: _site

website:
  title: "Hypnodingues"
  site-url: "https://hypnodingues.org"
  navbar:
    left:
      - href: posts/index.qmd
        text: Articles

format:
  html:
    theme: cyborg
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
    include-after-body:
      - text: |
          <script src="assets/js/prev_next_buttons.js"></script>
          <script src="assets/js/target_blank.js"></script>
          <!-- <script src="assets/js/file_list.js"></script> -->

