---
layout: post
title: 6 mars 2011, Hypnose collective chez Dominique
date: 2012-03-09 21:18:14.000000000 +01:00
categories:
- Hypnose
- Textes
tags: []
status: private
type: post
published: false
meta:
  _edit_last: '2'
author:
  first_name: Nico
excerpt:
---
<p>Vous êtes allongé confortablement. Vous pouvez remuer pour trouver la position qui vous convient le mieux. Trouvez une position où vous vous sentez bien. Les paumes de vos mains tournées vers le haut.</p>
<p>Alors la première chose à faire et vous le savez bien sûr, c'est de toujours prendre le temps de retrouver une respiration minimale, calme et régulière. Que ce soit toujours exactement pareil. Un peu comme si rien n'était plus important que cette absolue régularité de votre respiration. Très bien. Vous allez conserver cette respiration calme et régulière et vous allez maintenant pouvoir ouvrir les yeux et choisir un point à fixer à peu près en face de vous. Ce que vous préférez ou plus exactement ce qui vous fait plaisir.</p>
<p>Très bien. Une fois que vous avez choisi ce point alors vous allez le fixer avec vos yeux, vous allez l'accrocher avec vos yeux. Même quand il deviendra flou.</p>
<p>Très bien. Maintenant vous allez penser à cette respiration calme et régulière et à vos yeux accrochés à ce point que vous avez choisi.</p>
<p>Vous allez vous appliquer à voir sans bouger les yeux, tout ce qu'il y a au dessus de vous.</p>
<p>Très bien. Maintenant, toujours sans bouger les yeux bien sûr, tout ce qu'il y a au dessous de vous. Et puis tout ce qu'il y a à gauche de vous. Et enfin tout ce qu'il y a à droite.</p>
<p>Très bien. Maintenant en maintenant consciemment cette respiration calme et régulière et vos yeux accrochés au point que vous avez choisi, vous allez vous appliquer à voir toujours sans bouger les yeux bien sûr, l'étendue complète de votre champ de vision. C'est-à-dire que vous ne regardez plus rien mais vous voyez tout de haut en bas et de gauche à droite et tout est un peu flou.</p>
<p>Voilà, très bien. Cela s'appelle, vous le savez, la vision périphérique. Alors vous allez conserver cette vision périphérique ainsi que votre respiration calme et régulière et vous allez maintenant en plus et en même temps prêter attention aux sensations vous provenant de votre corps. Par exemple : l'appui de vos fesses contre le sol et puis l'appui de vos talons et de vos pieds. Si vous étiez comme moi en position assise cela pourrait être l'appui de vos pieds contre le sol bien sûr. L'appui ou la position de vos jambes. L'appui de votre dos. L'appui de votre tête ainsi que la position de votre tête. La position de vos bras, l'appui de vos bras. L'appui de vos mains. La position de vos mains, l'appui de vos mains ainsi que toutes les sensations qui vous parviennent peut-être déjà le long de vos doigts. Qu'il s'agisse de picotements, de fourmillement, d'engourdissement ou même de sensations de pulsation, de chaud et froid.</p>
<p>Très bien. Maintenant de manière plus générale, plus globale, la position de votre corps ainsi même que sa disposition.</p>
<p>Très bien. Vous allez maintenant pouvoir tranquillement fermer les yeux, tout en conservant bien sûr votre vision périphérique à travers vos paupières fermées. Ce qui vous permet peut-être déjà de percevoir des zones lumineuses ou des petits points lumineux qui s'allument un peu partout, un peu comme un ciel étoilé, un soir d'été.</p>
<p>Alors vous allez conserver la respiration calme et régulière, les sensations du corps et la vision périphérique et son ciel étoilé et vous allez maintenant en plus et en même temps prêter attention le plus précisément possible, note après note, vague après vague à cette musique.</p>
<p>Et tout en conservant votre attention sur cette musique, vous allez également, prêter attention à tous les autres bruits éventuels.</p>
<p>Voilà. Et c'est ainsi que le plus simplement, le plus naturellement du monde vous atteignez petit à petit cet état que vous découvrez et que vous connaissez déjà un peu. Où le conscient et l'inconscient se retrouvent et la porte s'ouvre. C'est un accès tout à la fois à votre passé bien sûr, mais également et surtout à vos immenses ressources qui sont là à portée de vous.</p>
<p>Et le plus surprenant, je vous le concède tout à fait c'est que apparemment rien à changé. Et pourtant la différence est essentielle bien sûr, car désormais tout devient possible.</p>
<p>C'est un état de force et de douceur, de paix et d'amour, de bien-être, essentiel et profond qui tout doucement va commencer à s'installer à partir de maintenant. Et le premier à s'en rendre compte, c'est votre corps bien sûr qui a peut-être déjà commencé à se relâcher et se détendre et qui de respiration en respiration va se relâcher et se détendre plus encore. Se détendre et s'engourdir, s'engourdir et tout doucement s'alourdir au point de vous donner bientôt l'impression qu'il appuie d'avantage.</p>
<p>Voilà. Et c'est ainsi que tout votre corps depuis vos paupières jusqu'à vos pieds s'installe à chaque respiration un peu plus dans un repos calme, profond, serein et lourd. Un vrai repos et c'est très agréable.</p>
<p>D'ailleurs, vous sentez peut-être déjà tout doucement de mieux en mieux et même bientôt carrément bien. Car tout va devenir et continuer à devenir de jour en jour tellement plus simple et plus facile, tellement plus agréable.</p>
<p>Et c'est un peu normal bien sûr, car plus votre corps est au repos et plus votre esprit est libre. Libre et attentif. Attentif au son de ma voix qui n'est que l'écho de la vôtre et libre de faire très exactement tout ce que vous avez envie de faire aux seules conditions d'en avoir envie et que se soit bon pour vous.</p>
<p>Alors je vous propose de faire une expérience. Si les paumes de vos mains sont tournées vers le bas, vous pouvez doucement les tourner vers le haut. Maintenant, vous pouvez ressentir de plus en plus intensément l'air au contact de la peau à l'intérieur de vos mains. Autorisez-vous à ressentir toutes les sensations qui vous proviennent de vos paumes. Il se peut que vous ressentiez des pulsations, des vibrations, des chatouillements, un changement de température. Laissez toute votre attention focalisée sur votre peau et les sensations que vous pouvez ressentir. Appréciez les variations, petites ou grandes, de ces sensations. Si vous le voulez, vous pouvez maintenant rapprocher vos deux mains sans qu'elles ne se touchent. Puis vous pouvez les éloigner. Et pendant que vos mains s'approchent et s'éloignent, vous pouvez garder toute votre attention focalisée sur les sensations que vous ressentez à la surface de votre peau. Peut-être que les sensations diminuent lorsque vos mains se rapprochent ou peut-être qu'elles augmentent. Toute sensation est juste. Et peut-être que vos mains rencontrent des couches de résistance différentes. Tout cela est parfait.</p>
<p>Maintenant, vous pouvez décider que ce que vous ressentez est de l'énergie. Vous le saviez ou peut-être que vous vous en doutiez, nous sommes tous des êtres d'énergie. Même la célèbre équation E = mc2 d'Einstein nous le confirme : la matière et l'énergie ne sont que deux aspects d'une même réalité. Et vous pouvez décider que l'expérience que vous venez de faire est une invitation subjective à ressentir cette énergie. Et si votre corps contient autant d'énergie, vous allez pouvoir l'utiliser à votre avantage, dans votre vie, pour la guérison.</p>
<p>Nous allons maintenant nous élever vers un état alpha de qualité supérieure. Je vous propose que vous vous imaginiez que vous tenez une craie dans la main avec laquelle vous écrivez normalement. Et vous pouvez faire le geste d'inscrire le chiffre 1 sur un tableau noir imaginaire devant vous. Je vous laisse faire ce geste. Voilà. Maintenant que vous avez inscrit ce chiffre au tableau devant vous, vous pouvez l'effacer du revers de la même main qui l'a inscrit. Je vous invite maintenant a inscrire le chiffre 2. Voilà, très bien. Vous pouvez maintenant l'effacer du revers de la même main. Et vous pouvez continuer ainsi à inscrire des chiffres toujours plus grands, sur ce tableau noir imaginaire. À votre rythme. Lorsque votre bras sera lourd ou que vous estimiez que vous êtes allé assez loin ou encore si je vous le demande, vous pourrez arrêter d'inscrire ces chiffres. Je vous laisse faire et je reprendrai la parole dans quelques instants. Allez-y, à votre rythme.</p>
<p>Voilà. Je vous propose maintenant d'utiliser votre énergie et de la mettre en commun avec celles des autres participants. Vous allez, si vous le voulez participer à une expérience de guérison. Je vous propose que vous vous imaginiez que vous vous tenez debout derrière Dominique. Toi aussi Dominique, tu peux t'imaginer que tu te tiens debout derrière toi-même. Toujours par la pensée, vous tournez vos paumes vers le ciel et vous pouvez ressentir l'énergie dans le creux de vos mains. Maintenant vous vous penchez de façon à ce que vos yeux se trouvent à environ trente centimètres de la tête de Dominique. Vous placez vos mains en coupe sur le sommet de son crâne sans le toucher. Tout en ressentant l'énergie canalisée par vos mains, vous pouvez vous imaginer que de la lumière blanche sort de vos yeux et entre dans le sommet de la tête de Dominique. Et vous pouvez voir cette lumière qui illumine l'intérieur de la tête de Dominique. Et vous pouvez vous imaginer que vous rapetissez et que vous entrez dans la tête de Dominique. Voilà, vous êtes tout petit et vous êtes dans la tête de Dominique. Vous pouvez vous imaginer que vous êtes en possession d'un objet fabuleux qui envoie de la lumière blanche. Mon objet à moi, c'est un parapluie qui envoie de la lumière chaque fois que je l'ouvre et le ferme. Je vous laisse choisir votre objet qui envoie de la lumière blanche. Si vous n'avez pas d'objet à l'esprit, prenez simplement une lampe de poche. Voilà, et maintenant vous allez envoyer de la lumière dans chacun des recoins du cerveau de Dominique. Et tout ce qui était sombre s'illumine, partie par partie. Tout ce qui était noir, est maintenant en train d'être illuminé par vous et l'objet que vous avez choisi. Je vous invite à vous souvenir de toutes les sensations que vous ressentirez lors de cette expérience. Toutes les impressions vous informent sur la perception subjective que vous avez de Dominique et vous pourrez lui raconter une fois cette expérience terminée. Maintenant, vous pouvez vous imaginer en train d'envoyer cette douce lumière blanche dans toutes les différentes parties de la tête de Dominique.</p>
<p>Voilà, maintenant vous pouvez décider que cette expérience est une véritable expérience de guérison. Vous êtes tous des guérisseurs, chaque partie de vous est de l'énergie. Chacune de vos pensées est de l'énergie. Et l'amour que vous ressentez et que vous envoyez à Dominique est aussi de l'énergie. Je vous laisse ressentir cette énergie d'amour qui s'écoule de vous alors que vous êtes tout petit dans la tête maintenant illuminée de Dominique.</p>
<p>Vous allez maintenant illuminer chacune des parties du corps de Dominique. Vous descendez donc dans son cou. Dans son épaule gauche, son bras gauche jusqu'au poignet et finalement la main. Vous notez intérieurement toutes les sensations que vous ressentez et vous appréciez la qualité de cette lumière très pure que vous envoyez à Dominique. Puis vous revenez dans son épaule droite, son bras droite jusqu'au poignet et finalement la main. Vous revenez au buste et vous éclairez tous ses organes : le coeur, les poumons, puis plus bas les organes du ventre. Vous ressentez profondément la qualité de cette lumière et vous en rayonnez la quintessence : l'amour. Car l'amour guérit et tout peut être guérit. Vous descendez maintenant dans la jambe gauche et notez toutes les sensations que vous pouvez ressentir. Vous pouvez aller jusqu'au pied. Bien, maintenant, vous remontez et faites de même avec la jambe droite.</p>
<p>Voilà, très bien. Je vais maintenant passer en revue chacun des sept chakras du corps humain. Vous le savez peut-être, les chakras sont une représentation métaphoriques des différentes parties du corps. On associe à chacun d'eux une couleur et une note de musique. Ils sont situé chacun sur un plexus, c'est-à-dire un rassemblement de nerfs et de vaisseaux. Et à chacun d'entre eux on associe une glande, un système corporel, un élément terrestre, un sens et certains champs de conscience spécifiques.</p>
<p>Le chakra rouge en premier est situé où se trouve le périnée, c'est-à-dire entre les organes sexuels et l'anus. Vous pouvez, par la pensée vous mettre à genoux à côté de Dominique et placer une main derrière elle à dix centimètres à la hauteur du chakra rouge. Et vous pouvez, toujours par la pensée, vous imaginer le chakra rouge de Dominique. C'est une boule et vous pouvez la percevoir. Notez la couleur qui vous vient en premier à l'esprit. Retenez cette couleur, vous pourrez en parler avec Dominique à la fin de cette expérience de guérison. Si cette couleur n'est pas le rouge, j'aimerais que par la pensée, vous la transformiez en rouge. Vous pouvez utiliser le moyen qu'il vous plaira : un pinceau, un spray ou juste votre pensée. Voilà, vous pouvez décider que maintenant le chakra rouge de Dominique est effectivement rouge et qu'il respire toutes les qualités qui lui sont associées : la sûreté, la sécurité, la confiance, la survie, l'argent, le foyer et le travail.</p>
<p>Vous pouvez maintenant vous déplacer et toujours à genoux, tout en regardant dans la même direction que Dominique, vous pouvez poser une main sur chacun de ses genoux. Maintenant vous pouvez visualiser une lumière rouge qui s'écoule de son chakra rouge le long du haut de ses jambes, jusqu'à ses genoux. Ressentez la perfection de cette lumière rouge qui illumine l'intérieur de ses jambes. maintenant, par la pensée, vous placez vos mains sur le dessus de ses pieds. Et vous faites circuler la lumière de son chakra rouge le long de ses jambes jusqu'à ses pieds. Ressentez profondément la qualité de cette lumière rouge qui s'écoule librement le long des jambes de Dominique. Maintenant vous allez envoyer cette lumière dans la terre où elle va, comme les racines d'un arbre, partir dans toutes les directions. Créez des racines de lumières vigoureuses, grandes qui fortifient déjà Dominique. La nourrissent et l'ancre dans la réalité. Bien, maintenant imaginez-vous que le centre de la terre est une énorme boule rouge. Rouge comme le chakra rouge. Et imaginez que la lumière qui vient du chakra rouge de Dominique et passe le long de ses jambe et à travers de ses pieds s'engouffre dans un canal qui la mène tout droit vers cette boule au centre de la terre. Oui cette lumière s'écoule librement du chakra rouge de Dominique au centre de la terre et le remplit de cette lumière rouge. Il se peut que vous perceviez une autre couleur que le rouge. Si c'est le cas changez par la pensée la couleur et rappelez-vous de votre perception initiale pour en informer Dominique à la fin de cette expérience de guérison. Maintenant vous pouvez décider que la lumière est rouge et que Dominique a envoyé une quantité de lumière phénoménale de son chakra vers le centre de la terre. Maintenant c'est à la terre de nourrir Dominique. Imaginez que la lumière s'écoule maintenant dans l'autre sens. C'est le centre de la terre qui envoie la lumière à Dominique. Et les racines aussi renvoient leur lumière à Dominique. Et c'est une quantité incroyable de lumière qui revient vers elle. Et vos mains toujours posées sur ses pieds peuvent ressentir cette énergie de lumière et de guérison que la terre offre à Dominique. Et toujours en focalisant votre attention sur cette énergie lumineuse qui s'écoule du centre de la terre et des racines, notez toutes les sensations aux niveaux de vos mains posées sur les pieds de Dominique. Notez toutes les impressions et si une image vous vient à l'esprit, souvenez-vous en. Vous pourrez en informer Dominique à la fin de cette expérience de guérison. Posez maintenant vos mains sur les genoux de Dominique et faites ressentez la lumière qui s'écoule à l'intérieur de ses jambes du centre de la terre et des racines jusqu'à son chakra rouge. Puis placez une main derrière elle à dix centimètres au niveau de son chakra rouge et visualisez son chakra rouge et toute la lumière qu'il reçoit.</p>
<p>Mais je vous raconterais bien aussi l'histoire de Frédérique. Frédérique adorait son grand-père. Il ne pouvait retenir son impatience lorsque chaque dimanche, ils allaient, avec ses parents, à la campagne, rejoindre son « pépé ». Lorsqu'ils arrivaient cependant, Frédérique ne montrait plus rien de cette joie qu'il avait au fond de lui. Et pourtant il adorait, quand pépé lui lisait des contes fantastiques au coin du feu, les dimanches de pluie. Mais il ne le montrait pas. Et s'il faisait beau, son cœur bondissait de joie rien qu'à l'idée que pépé l'emmènerait au ruisseau et qu'ils y construiraient un barrage qui lui semblerait énorme. Mais là encore, Frédérique, malgré son bonheur, ne montrait rien à son grand-père.</p>
<p>Vous pouvez maintenant par la pensée, visualiser le chakra orange de Dominique. Ce chakra est situé au centre de l'abdomen ou si vous préférez au niveau du nombril. Vous pouvez par la pensée placer une main devant Dominique et l'autre derrière toutes les deux à environ dix centimètres et au niveau du chakra orange. Et vous allez visualiser ce chakra et noter de quelle couleur vous le voyez. Si ce n'est pas la couleur orange, vous pouvez par la pensée changer cette couleur et la transformer en orange. Vous pouvez vous représenter les champs de conscience liés à ce chakra. Ces champs sont : les sensations, le ressenti, les sentiments, la nourriture, le sexe et l'appétit. Maintenant vous pouvez décider que le chakra est effectivement orange et qu'il apporte à Dominique toute les qualités qui lui sont associées.</p>
<p>Le temps s'écoulait. Frédérique grandissait. Et un jour son grand-père tomba tellement malade, qu'il fallu l'opérer de toute urgence. Et patatra, l'opération échoua et pépé mourut.</p>
<p>Frédérique ne montra pas sa peine. Il fit comme avec sa joie. Il la garda à l'intérieur de lui. Et pendant bien des années il en voulu beaucoup à son grand-père d'être parti sans même lui dire au-revoir.</p>
<p>Mais une nuit, il fit un rêve étrange. Son pépé flottait au-dessus de son lit et brillait d'une lumière douce. Frédérique reconnu tout de suite les traits de son visage et le son de sa voix. Dans son rêve, Frédérique ne pu s'empêcher de sangloter et de lui reprocher d'être parti sans même lui dire au-revoir.</p>
<p>jaune</p>
<p>Et son pépé lui répondit de la même voix pleine de tendresse que Frédérique lui connaissait, qu'il était parti pendant l'opération parce que pour lui s'était le plus facile. Il était endormi à ce moment-là et il était donc sûr de quitter cette vie de la meilleure manière qui soit et sans souffrir. Mais maintenant, il voyait la peine de Frédérique et avait demandé l'autorisation de revenir, sous la forme d'un ange, dans un rêve de Frédérique pour lui demander pardon.</p>
<p>vert</p>
<p>« Alors c'est vrai, » demanda Frédérique « tu es revenu me demander pardon ? ». « Oui. » répondit son grand-père. « Je suis revenu te demander pardon, parce que je ne savais pas que tu tenais tellement à moi et que je te ferai tellement de peine en partant sans te dire au-revoir. »</p>
<p>bleu</p>
<p>Alors Frédérique, toujours dans son rêve, remercia pépé d'être revenu lui expliquer. Il lui pardonna complètement d'être parti sans lui dire au-revoir. Et il lui dit aussi qu'il avait bien fait de partir pendant l'opération, car comme ça, maintenant Frédérique savait qu'il n'avait pas souffert.</p>
<p>indigo</p>
<p>Et Frédérique n'en voulu plus jamais à son grand-père. Il prit même une décision. Une décision qui changea toute sa vie. Il décida qu'à partir de maintenant, il ferait son maximum pour montrer à tout ceux qu'il aimait, même ceux qu'il aimait qu'un petit peu, qu'il les aimait de tout son cœur.</p>
